### PR TITLE
Fixed Config annotation not sticking at runtime and added CommandRegistry

### PR DESCRIPTION
**Pull request by Ascynx**
added a command thing and fixed config not actually loading properly

### CODE REVIEW

**Comment by Ascynx** [comment]
oh sorry to the people I mentionned

**Comment by DalwynWasTaken** [comment]
Why did you lock it to contributors?

**Comment by Ascynx** [comment]
I mentionned an organisation, I don't want to deal with notifications

**Comment by Ascynx** [comment]
was an accident btw

**Review by DalwynWasTaken — CHANGES_REQUESTED** [review]
I realise this happened because you imported new classes but you made all the java.io a wildcard import. You’ll need to go through making them all individual imports. Otherwise it looks good

**Review by DalwynWasTaken — APPROVED** [review]

**Pull request merged**
